### ISSUE TITLE
株価をわかりやすくして欲しい。

### ISSUE THREAD

**Issue by plump-aa** [Yasuko/kabu#1]
できればリアルタイム株価みみたい。

**Comment by Yasuko** [comment]
課題が多い案件になるとです。
・分単位まで取れるが、データ量が360倍になるので、DBがピンチ
・データの取得に1時間あたり2000回のコール制限があるので、全件は取れない
・データの取得漏れが最低5％程度あるので、歯抜けデータがグラフに反映される

この辺の解決策が見えれば対応しやす

**Comment by plump-aa** [comment]
その部分は外部のツールを表示してもいいかも。

**Comment by Yasuko** [comment]
![image](https://github.com/user-attachments/assets/c92ded18-585b-49ec-a5b6-56913a88461b)
グラフの日付、Open価格履歴、Vokumes履歴、企業名の表記を追加し
多分見やすくなった。ということで一旦Close
